### PR TITLE
module: add ngx_slab_stat module

### PR DESCRIPTION
**Pull request by hongxiaolong**
module: add ngx_slab_stat module

### CODE REVIEW

**Comment by hongxiaolong** [comment]
slab_stat.patch dont be needed with this PR: https://github.com/alibaba/tengine/pull/923

**Comment by hongxiaolong** [comment]
* Tested-by: HONGXIAOLONG hongxiaolong
* Date: Wed Aug 30 11:31:10 CST 2017
* hostname: hongxiaolong
* pwd: /Users/hongxiaolong/Projects/GitHub/hongxiaolong/tengine/modules/ngx_slab_stat
* cases: `t/test.t`
* git log:

```
commit ade320568cd8d0697f4e859921eede43104da504
Author: HONGXIAOLONG <imhongxiaolong@gmail.com>
Date:   Wed Aug 30 11:14:26 2017 +0800

    module: add ngx_slab_stat module

```

* case result:

```
$ MOD_DYCONF_PATH=/Users/hongxiaolong/Projects/GitHub/hongxiaolong/tengine/modules/ngx_slab_stat TEST_NGINX_BINARY=/Users/hongxiaolong/Projects/GitHub/hongxiaolong/tengine/objs/nginx prove -I /Users/hongxiaolong/Projects/GitHub/hongxiaolong/tengine/tests/nginx-tests/nginx-tests/lib t/test.t
t/test.t .. ok
All tests successful.
Files=1, Tests=3,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.05 cusr  0.01 csys =  0.09 CPU)
Result: PASS
```

* Report-generated-by: http://wxc.oss.aliyuncs.com/dtest.sh

**Comment by chobits** [comment]
ack

**Comment by taoyuanyuan** [comment]
ack

**Pull request merged**
