### PR TITLE
SPDY: updated to official nginx SPDY/3.1 implementation

### PR DESCRIPTION
**Pull request by chobits**
The old spdy module (SPDY/2 & SPDY/3) is deprecated.
The document of SPDY/3.1 module is available [here](http://nginx.org/en/docs/http/ngx_http_spdy_module.html).

The listen option `spdy_detect` can still be used.

### CODE REVIEW

**Comment by chobits** [comment]
The [spdy.t](http://hg.nginx.org/nginx-tests/file/c2481c6b748f/spdy.t) case passed. 
More details are available here:
```
~ $ sh nginx_test.sh
TEST_NGINX_BINARY=objs/nginx prove -v -I /home/xiaochen/tengine/tests/nginx-tests/nginx-tests/lib /home/xiaochen/tengine/tests/nginx-tests/nginx-tests/spdy.t
./tests/nginx-tests/nginx-tests/spdy.t ..
1..82
ok 1 - PING frame
ok 2 - PING payload
ok 3 - SYN_REPLAY frame
ok 4 - SYN_REPLAY stream
ok 5 - SYN_REPLAY status
ok 6 - SYN_REPLAY header
ok 7 - DATA frame
ok 8 - DATA length
ok 9 - DATA payload
ok 10 - SYN_REPLAY stream 2
ok 11 - SYN_REPLAY status 2
ok 12 - SYN_REPLAY header 2
ok 13 - DATA frame 2
ok 14 - SYN_REPLAY stream 2
ok 15 - DATA length 2
ok 16 - DATA payload 2
ok 17 - SYN_REPLAY stream HEAD
ok 18 - SYN_REPLAY status HEAD
ok 19 - SYN_REPLAY header HEAD
ok 20 - HEAD no body
ok 21 - PROXY SYN_REPLAY frame
ok 22 - PROXY remote addr
ok 23 - SYN_REPLAY status range
ok 24 - DATA length range
ok 25 - DATA payload range
ok 26 - multiple request header values # TODO not yet
ok 27 - multiple request header values - proxied # TODO not yet
ok 28 - response header with multiple values
ok 29 - no empty header value inside # TODO not yet
ok 30 - no empty header value first # TODO not yet
ok 31 - no empty header value last # TODO not yet
ok 32 - spdy variable
ok 33 - chunk_size body chunks
ok 34 - chunk_size body 1
ok 35 - chunk_size body 2
ok 36 - chunk_size body 3
ok 37 - chunk_size body 4
ok 38 - SYN_REPLAY status with redirect
ok 39 - DATA frame with redirect
ok 40 - DATA payload with redirect
ok 41 - proxy cache HEAD - no body
not ok 42 - proxy cache headers only # TODO premature client connection close
#   Failed (TODO) test 'proxy cache headers only'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 339.
ok 43 - proxy cache HEAD buffering off - no body
ok 44 - proxy cache unconditional
ok 45 - proxy cache conditional
ok 46 - request body
ok 47 - proxied response length
ok 48 - proxied response
ok 49 - iws - stream blocked on initial window size
ok 50 - iws - PING not blocked
ok 51 - iws - updated stream window
ok 52 - iws - updated connection window
ok 53 - increased initial window size
ok 54 - negative window - no data
ok 55 - zero window - no data
ok 56 - positive window - data
ok 57 - positive window - data length
ok 58 - multiple - stream1 data
ok 59 - multiple - stream2 no data
ok 60 - multiple - stream1 remain data
ok 61 - multiple - stream2 full data
ok 62 - priority 0
ok 63 - priority 1
ok 64 - priority 7
ok 65 - multiple priority 1
ok 66 - multiple priority 2
ok 67 - conn_limit 1
ok 68 - conn_limit 2
ok 69 - RST_STREAM 1
ok 70 - RST_STREAM 2
not ok 71 - even stream - GOAWAY frame # TODO not yet

#   Failed (TODO) test 'even stream - GOAWAY frame'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 594.
not ok 72 - even stream - error code # TODO not yet

#   Failed (TODO) test 'even stream - error code'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 595.
#          got: undef
#     expected: '1'
not ok 73 - even stream - last used stream # TODO not yet

#   Failed (TODO) test 'even stream - last used stream'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 596.
#          got: undef
#     expected: '0'
not ok 74 - backward stream - GOAWAY frame # TODO not yet
#   Failed (TODO) test 'backward stream - GOAWAY frame'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 613.
not ok 75 - backward stream - error code # TODO not yet

#   Failed (TODO) test 'backward stream - error code'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 614.
#          got: undef
#     expected: '1'
not ok 76 - backward stream - last used stream # TODO not yet

#   Failed (TODO) test 'backward stream - last used stream'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 615.
#          got: undef
#     expected: '3'
not ok 77 - dup stream - RST_STREAM frame # TODO not yet

#   Failed (TODO) test 'dup stream - RST_STREAM frame'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 631.
not ok 78 - dup stream - error code # TODO not yet

#   Failed (TODO) test 'dup stream - error code'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 632.
#          got: undef
#     expected: '1'
not ok 79 - dup stream - stream # TODO not yet

#   Failed (TODO) test 'dup stream - stream'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 633.
#          got: undef
#     expected: '3'
ok 80 - awkward version
ok 81 - incomplete headers
not ok 82 - GOAWAY on connection close # TODO not yet
#   Failed (TODO) test 'GOAWAY on connection close'
#   at ./tests/nginx-tests/nginx-tests/spdy.t line 665.
ok
All tests successful.

Test Summary Report
-------------------
./tests/nginx-tests/nginx-tests/spdy.t (Wstat: 0 Tests: 82 Failed: 0)
  TODO passed:   26-27, 29-31
  Files=1, Tests=82,  3 wallclock secs ( 0.04 usr  0.01 sys +  0.20 cusr  0.10 csys =  0.35 CPU)
  Result: PASS
```

**Comment by ym** [comment]
Hi, is this commit incomplete?
Can't build with this commit ...

configure arguments: --with-http_ssl_module --with-http_spdy_module 

```
src/http/ngx_http_request.c: In function ‘ngx_http_ssl_handshake_handler’:
src/http/ngx_http_request.c:914:17: error: ‘ngx_http_spdy_srv_conf_t’ has no member named ‘version’
         if (sscf->version == NGX_SPDY_VERSION_V3) {
                 ^
src/http/ngx_http_request.c:914:30: error: ‘NGX_SPDY_VERSION_V3’ undeclared (first use in this function)
         if (sscf->version == NGX_SPDY_VERSION_V3) {
                              ^
src/http/ngx_http_request.c:914:30: note: each undeclared identifier is reported only once for each function it appears in
In file included from src/core/ngx_core.h:45:0,
                 from src/http/ngx_http_request.c:9:
src/http/ngx_http_request.c:915:32: error: ‘NGX_SPDY_V3_NPN_NEGOTIATED’ undeclared (first use in this function)
             ngx_str_set(&spdy, NGX_SPDY_V3_NPN_NEGOTIATED);
                                ^
src/core/ngx_string.h:43:25: note: in definition of macro ‘ngx_str_set’
     (str)->len = sizeof(text) - 1; (str)->data = (u_char *) text
```

**Comment by chobits** [comment]
hi @ym,
Thanks for your report, we will fix that soon.

**Comment by chobits** [comment]
hi @ym,
we have fixed the problem you reported in https://github.com/alibaba/tengine/pull/591.

**Pull request merged**
