### PR TITLE
test: Remove string.t

### PR DESCRIPTION
**Pull request by u5surf**
* the location which includes `%le` sequence only skip `%`
* thus  the case of `se%lect` just becomes `select`.

The sequence has reached｀%`, it skips and breaks in L.1668 and it scans next character.

The next character is `l`, it unstatisfies 0-9a-f, then the state has become sw_usual and the `l` has stored the dst in L.1691-L.1693.
Finally, `se%lect` becomes simply `select`.
https://github.com/alibaba/tengine/blob/c2e166a39287a41ec91ece95ec579c9042603d53/src/core/ngx_string.c#L1657-L1695

Signed-off-by: u5surf <u5.horie@gmail.com>

### CODE REVIEW

**Comment by chobits** [comment]
Hi, I am also looking at this case. Then you can remove this case because it is deprecated. See following:


    This test cases was used to test old tengine feature, as following:

    ```
        commit ca58fa3a038cd932e8152d9307be07f7918b5260
        Author: Weibin Yao <yaoweibin@gmail.com>
        Date:   Wed Apr 17 12:10:42 2013 +0800
        fixed the missing with invalid character for ngx_unescape_uri
    ```

    After we removed this feature when we upgraded tengine core to
    nginx-1.8.x, the case string.t is deprecated.

**Comment by chobits** [comment]
also note that , if you cannot pass **tests/nginx-tests/tengine-tests/ngx_dtls.t**  for some reason, you can just skip it in ci.yml.
It is a standalone project for DTLS https://github.com/Tongsuo-Project/Tongsuo, which should be tested by their team

**Comment by u5surf** [comment]
@chobits I removed string.t in this PR. Can you check again please?

**Comment by chobits** [comment]
Thanks, ack

**Pull request merged**
