### PR TITLE
Merge nginx 1.8.0 to 1.8.1

### PR DESCRIPTION
**Pull request by magicbear**

### CODE REVIEW

**Comment by cloudcache** [comment]
mb放弃吧。。。。没人理睬你啊

**Comment by chobits** [comment]
Sorry for late reply. We are looking into this pr and trying to run all the tests cases in tests/ for this patch. And tests/nginx-tests/nginx-tests have been passed. We'll run cases in tests/test-nginx later.

---
All test cases except spdy.t in tests/nginx-tests/nginx-tests have been passed.
(We use http2 module instead of spdy for this test.)

See the following log for details:

```
$ cd tengine
$ cat genmake.sh
./configure --prefix=$(pwd)/output --with-debug \
            --with-ipv6 \
            --with-mail \
            --with-http_v2_module \
            --with-http_realip_module \
            --with-http_lua_module \
            --with-http_auth_request_module \
            --with-http_gunzip_module \
            --with-http_addition_module \
            --with-http_secure_link_module \
            --with-http_xslt_module \
            --with-http_mp4_module \
            --with-http_flv_module \
            --with-http_dav_module \
            --with-http_sub_module \
            --with-http_perl_module \
            --with-http_random_index_module \
            --with-http_gzip_static_module \
$ sh genmake.sh
$ make -j
$ sudo make install

$ cat dtest.sh
nginx_src=$(pwd)
nginx_bin=$nginx_src/objs/nginx
nginx_test_lib=$nginx_src/tests/nginx-tests/nginx-tests/lib
nginx_case=tests/nginx-tests/nginx-tests

if [ "$1" != "" ]; then
  nginx_case=$1
fi

TEST_NGINX_BINARY="$nginx_bin" prove -I $nginx_test_lib $nginx_case

$ sh dtest.sh tests/nginx-tests/nginx-tests/
tests/nginx-tests/nginx-tests/access.t ..................... ok
tests/nginx-tests/nginx-tests/addition.t ................... ok
tests/nginx-tests/nginx-tests/auth_basic.t ................. ok
tests/nginx-tests/nginx-tests/auth_request.t ............... ok
tests/nginx-tests/nginx-tests/auth_request_satisfy.t ....... ok
tests/nginx-tests/nginx-tests/auth_request_set.t ........... ok
tests/nginx-tests/nginx-tests/autoindex.t .................. ok
tests/nginx-tests/nginx-tests/body.t ....................... ok
tests/nginx-tests/nginx-tests/body_chunked.t ............... ok
tests/nginx-tests/nginx-tests/dav.t ........................ ok
tests/nginx-tests/nginx-tests/dav_chunked.t ................ ok
tests/nginx-tests/nginx-tests/debug_connection.t ........... ok
tests/nginx-tests/nginx-tests/empty_gif.t .................. ok
tests/nginx-tests/nginx-tests/error_log.t .................. ok
tests/nginx-tests/nginx-tests/fastcgi.t .................... ok
tests/nginx-tests/nginx-tests/fastcgi_body.t ............... ok
tests/nginx-tests/nginx-tests/fastcgi_buffering.t .......... ok
tests/nginx-tests/nginx-tests/fastcgi_cache.t .............. ok
tests/nginx-tests/nginx-tests/fastcgi_header_params.t ...... ok
tests/nginx-tests/nginx-tests/fastcgi_keepalive.t .......... ok
tests/nginx-tests/nginx-tests/fastcgi_merge_params.t ....... nginx: [warn] no "fastcgi_cache_key" for "fastcgi_cache" in /tmp/nginx-test-Br4BSwRHwx/nginx.conf:46
nginx: [warn] no "fastcgi_cache_key" for "fastcgi_cache" in /tmp/nginx-test-Br4BSwRHwx/nginx.conf:46
nginx: [warn] no "fastcgi_cache_key" for "fastcgi_cache" in /tmp/nginx-test-Br4BSwRHwx/nginx.conf:46
tests/nginx-tests/nginx-tests/fastcgi_merge_params.t ....... ok
tests/nginx-tests/nginx-tests/fastcgi_merge_params2.t ...... nginx: [warn] no "fastcgi_cache_key" for "fastcgi_cache" in /tmp/nginx-test-IUWTWS53oQ/nginx.conf:41
nginx: [warn] no "fastcgi_cache_key" for "fastcgi_cache" in /tmp/nginx-test-IUWTWS53oQ/nginx.conf:41
tests/nginx-tests/nginx-tests/fastcgi_merge_params2.t ...... ok
tests/nginx-tests/nginx-tests/fastcgi_split.t .............. ok
tests/nginx-tests/nginx-tests/geo.t ........................ ok
tests/nginx-tests/nginx-tests/gunzip.t ..................... ok
tests/nginx-tests/nginx-tests/gunzip_memcached.t ........... ok
tests/nginx-tests/nginx-tests/gunzip_perl.t ................ ok
tests/nginx-tests/nginx-tests/gunzip_ssi.t ................. ok
tests/nginx-tests/nginx-tests/gunzip_static.t .............. ok
tests/nginx-tests/nginx-tests/gzip.t ....................... ok
tests/nginx-tests/nginx-tests/gzip_flush.t ................. ok
tests/nginx-tests/nginx-tests/h2.t ......................... ok
tests/nginx-tests/nginx-tests/http_disable_symlinks.t ...... ok
tests/nginx-tests/nginx-tests/http_error_page.t ............ ok
tests/nginx-tests/nginx-tests/http_expect_100_continue.t ... ok
tests/nginx-tests/nginx-tests/http_host.t .................. ok
tests/nginx-tests/nginx-tests/http_location.t .............. ok
tests/nginx-tests/nginx-tests/http_location_auto.t ......... ok
tests/nginx-tests/nginx-tests/http_location_win32.t ........ skipped: not win32
tests/nginx-tests/nginx-tests/http_raw_uri_variable.t ...... ok
tests/nginx-tests/nginx-tests/http_resolver.t .............. Use of implicit split to @_ is deprecated at (eval 14) line 2.
Use of implicit split to @_ is deprecated at (eval 16) line 2.
tests/nginx-tests/nginx-tests/http_resolver.t .............. 1/32 Use of implicit split to @_ is deprecated at (eval 18) line 2.
tests/nginx-tests/nginx-tests/http_resolver.t .............. 4/32 Use of implicit split to @_ is deprecated at (eval 20) line 2.
tests/nginx-tests/nginx-tests/http_resolver.t .............. 9/32 Use of implicit split to @_ is deprecated at (eval 22) line 2.
Use of implicit split to @_ is deprecated at (eval 24) line 2.
Use of implicit split to @_ is deprecated at (eval 26) line 2.
Use of implicit split to @_ is deprecated at (eval 28) line 2.
Use of implicit split to @_ is deprecated at (eval 30) line 2.
Use of implicit split to @_ is deprecated at (eval 32) line 2.
Use of implicit split to @_ is deprecated at (eval 14) line 2.
Use of implicit split to @_ is deprecated at (eval 34) line 2.
Use of implicit split to @_ is deprecated at (eval 36) line 2.
tests/nginx-tests/nginx-tests/http_resolver.t .............. 21/32 Use of implicit split to @_ is deprecated at (eval 38) line 2.
Use of implicit split to @_ is deprecated at (eval 40) line 2.
Use of implicit split to @_ is deprecated at (eval 42) line 2.
tests/nginx-tests/nginx-tests/http_resolver.t .............. 27/32 Use of implicit split to @_ is deprecated at (eval 44) line 2.
tests/nginx-tests/nginx-tests/http_resolver.t .............. ok
tests/nginx-tests/nginx-tests/http_resolver_aaaa.t ......... Use of implicit split to @_ is deprecated at tests/nginx-tests/nginx-tests/http_resolver_aaaa.t line 593.
tests/nginx-tests/nginx-tests/http_resolver_aaaa.t ......... 1/72 Use of implicit split to @_ is deprecated at (eval 14) line 2.
Use of implicit split to @_ is deprecated at (eval 16) line 2.
Use of implicit split to @_ is deprecated at (eval 18) line 2.
Use of implicit split to @_ is deprecated at (eval 20) line 2.
Use of implicit split to @_ is deprecated at (eval 22) line 2.
Use of implicit split to @_ is deprecated at (eval 24) line 2.
Use of implicit split to @_ is deprecated at (eval 26) line 2.
tests/nginx-tests/nginx-tests/http_resolver_aaaa.t ......... ok
tests/nginx-tests/nginx-tests/http_server_name.t ........... ok
tests/nginx-tests/nginx-tests/http_time_http_variable.t .... ok
tests/nginx-tests/nginx-tests/http_try_files.t ............. ok
tests/nginx-tests/nginx-tests/http_variables.t ............. ok
tests/nginx-tests/nginx-tests/if_numeric_comparison.t ...... ok
tests/nginx-tests/nginx-tests/index.t ...................... ok
tests/nginx-tests/nginx-tests/limit_conn.t ................. ok
tests/nginx-tests/nginx-tests/limit_conn_complex.t ......... ok
tests/nginx-tests/nginx-tests/limit_req.t .................. ok
tests/nginx-tests/nginx-tests/mail_imap.t .................. ok
tests/nginx-tests/nginx-tests/mail_pop3.t .................. ok
tests/nginx-tests/nginx-tests/mail_resolver.t .............. Use of implicit split to @_ is deprecated at (eval 14) line 2.
tests/nginx-tests/nginx-tests/mail_resolver.t .............. 6/7 Use of implicit split to @_ is deprecated at (eval 14) line 2.
tests/nginx-tests/nginx-tests/mail_resolver.t .............. ok
tests/nginx-tests/nginx-tests/mail_smtp.t .................. ok
tests/nginx-tests/nginx-tests/mail_smtp_greeting_delay.t ... ok
tests/nginx-tests/nginx-tests/mail_smtp_xclient.t .......... ok
tests/nginx-tests/nginx-tests/map.t ........................ ok
tests/nginx-tests/nginx-tests/memcached.t .................. ok
tests/nginx-tests/nginx-tests/memcached_fake.t ............. ok
tests/nginx-tests/nginx-tests/memcached_keepalive.t ........ ok
tests/nginx-tests/nginx-tests/memcached_keepalive_stale.t .. ok
tests/nginx-tests/nginx-tests/mp4.t ........................ ok
tests/nginx-tests/nginx-tests/not_modified.t ............... ok
tests/nginx-tests/nginx-tests/perl.t ....................... ok
tests/nginx-tests/nginx-tests/perl_gzip.t .................. ok
tests/nginx-tests/nginx-tests/proxy.t ...................... ok
tests/nginx-tests/nginx-tests/proxy_cache.t ................ ok
tests/nginx-tests/nginx-tests/proxy_cache_chunked.t ........ ok
tests/nginx-tests/nginx-tests/proxy_cache_lock.t ........... ok
tests/nginx-tests/nginx-tests/proxy_cache_range.t .......... ok
tests/nginx-tests/nginx-tests/proxy_cache_revalidate.t ..... ok
tests/nginx-tests/nginx-tests/proxy_chunked.t .............. ok
tests/nginx-tests/nginx-tests/proxy_cookie.t ............... ok
tests/nginx-tests/nginx-tests/proxy_keepalive.t ............ ok
tests/nginx-tests/nginx-tests/proxy_merge_headers.t ........ ok
tests/nginx-tests/nginx-tests/proxy_next_upstream.t ........ ok
tests/nginx-tests/nginx-tests/proxy_next_upstream_tries.t .. 1/8 Use of implicit split to @_ is deprecated at (eval 14) line 2.
Use of implicit split to @_ is deprecated at (eval 16) line 2.
Use of implicit split to @_ is deprecated at (eval 18) line 2.
tests/nginx-tests/nginx-tests/proxy_next_upstream_tries.t .. ok
tests/nginx-tests/nginx-tests/proxy_noclose.t .............. ok
tests/nginx-tests/nginx-tests/proxy_protocol.t ............. ok
tests/nginx-tests/nginx-tests/proxy_redirect.t ............. ok
tests/nginx-tests/nginx-tests/proxy_set_body.t ............. ok
tests/nginx-tests/nginx-tests/proxy_ssl.t .................. ok
tests/nginx-tests/nginx-tests/proxy_store.t ................ ok
tests/nginx-tests/nginx-tests/proxy_unfinished.t ........... ok
tests/nginx-tests/nginx-tests/proxy_upgrade.t .............. ok
tests/nginx-tests/nginx-tests/proxy_websocket.t ............ ok
tests/nginx-tests/nginx-tests/proxy_xar.t .................. ok
tests/nginx-tests/nginx-tests/random_index.t ............... ok
tests/nginx-tests/nginx-tests/range.t ...................... ok
tests/nginx-tests/nginx-tests/range_charset.t .............. ok
tests/nginx-tests/nginx-tests/range_flv.t .................. ok
tests/nginx-tests/nginx-tests/range_if_range.t ............. ok
tests/nginx-tests/nginx-tests/range_mp4.t .................. ok
tests/nginx-tests/nginx-tests/realip.t ..................... ok
tests/nginx-tests/nginx-tests/referer.t .................... ok
tests/nginx-tests/nginx-tests/rewrite.t .................... ok
tests/nginx-tests/nginx-tests/rewrite_unescape.t ........... ok
tests/nginx-tests/nginx-tests/scgi.t ....................... ok
tests/nginx-tests/nginx-tests/scgi_body.t .................. ok
tests/nginx-tests/nginx-tests/scgi_cache.t ................. ok
tests/nginx-tests/nginx-tests/scgi_gzip.t .................. ok
tests/nginx-tests/nginx-tests/scgi_merge_params.t .......... nginx: [warn] no "scgi_cache_key" for "scgi_cache" in /tmp/nginx-test-2KlotWlThe/nginx.conf:48
nginx: [warn] no "scgi_cache_key" for "scgi_cache" in /tmp/nginx-test-2KlotWlThe/nginx.conf:48
nginx: [warn] no "scgi_cache_key" for "scgi_cache" in /tmp/nginx-test-2KlotWlThe/nginx.conf:48
tests/nginx-tests/nginx-tests/scgi_merge_params.t .......... ok
tests/nginx-tests/nginx-tests/secure_link.t ................ ok
tests/nginx-tests/nginx-tests/spdy.t ....................... skipped: spdy not compiled in
tests/nginx-tests/nginx-tests/split_clients.t .............. ok
tests/nginx-tests/nginx-tests/ssi.t ........................ ok
tests/nginx-tests/nginx-tests/ssi_if.t ..................... ok
tests/nginx-tests/nginx-tests/ssi_include_big.t ............ ok
tests/nginx-tests/nginx-tests/ssi_waited.t ................. ok
tests/nginx-tests/nginx-tests/ssl.t ........................ ok
tests/nginx-tests/nginx-tests/ssl_sni.t .................... ok
tests/nginx-tests/nginx-tests/sub_filter.t ................. ok
tests/nginx-tests/nginx-tests/sub_filter_perl.t ............ ok
tests/nginx-tests/nginx-tests/syslog.t ..................... ok
tests/nginx-tests/nginx-tests/upstream.t ................... ok
tests/nginx-tests/nginx-tests/upstream_ip_hash.t ........... ok
tests/nginx-tests/nginx-tests/upstream_least_conn.t ........ ok
tests/nginx-tests/nginx-tests/userid.t ..................... ok
tests/nginx-tests/nginx-tests/uwsgi.t ...................... ok
tests/nginx-tests/nginx-tests/xslt.t ....................... ok
tests/nginx-tests/nginx-tests/xslt_params.t ................ ok
All tests successful.

Test Summary Report
-------------------
tests/nginx-tests/nginx-tests/h2.t                       (Wstat: 0 Tests: 318 Failed: 0)
  TODO passed:   165, 236-239, 304
Files=122, Tests=1737, 135 wallclock secs ( 0.84 usr  0.32 sys + 32.90 cusr 10.78 csys = 44.84 CPU)
Result: PASS
```

**Comment by chobits** [comment]
Test cases for tengine modules have passed.

```
$ sh dtest.sh tests/nginx-tests/cases/
tests/nginx-tests/cases/concat.t ...................... ok
tests/nginx-tests/cases/consistent_hash.t ............. ok
tests/nginx-tests/cases/dynamic_resolve.t ............. ok
tests/nginx-tests/cases/dyups.t ....................... your test dir is /tmp/nginx-test-KcInNSzM9n at tests/nginx-tests/cases/dyups.t line 85.
tests/nginx-tests/cases/dyups.t ....................... ok
tests/nginx-tests/cases/fastcgi_check.t ............... ok
tests/nginx-tests/cases/fastcgi_no_buffering.t ........ 45/53 nginx: [warn] client_body_postpone_size 2097152 should be less than total postpone buffer size 65536 in /tmp/nginx-test-MO1e4jNHBC/nginx.conf:39
tests/nginx-tests/cases/fastcgi_no_buffering.t ........ ok
tests/nginx-tests/cases/gzip_clear_etag.t ............. ok
tests/nginx-tests/cases/http_error_page_merge.t ....... ok
tests/nginx-tests/cases/limit_req_enhance.t ........... ok
tests/nginx-tests/cases/reqstat.t ..................... 242 at tests/nginx-tests/cases/reqstat.t line 165.
tests/nginx-tests/cases/reqstat.t ..................... ok
tests/nginx-tests/cases/resolver.t .................... ok
tests/nginx-tests/cases/server_banner.t ............... ok
tests/nginx-tests/cases/session_sticky.t .............. ok
tests/nginx-tests/cases/slice.t ....................... skipped: slice not compiled in
tests/nginx-tests/cases/string.t ...................... ok
tests/nginx-tests/cases/sysguard.t .................... skipped: perl does not support threads
tests/nginx-tests/cases/upstream.t .................... ok
tests/nginx-tests/cases/upstream_keepalive_timeout.t .. ok
tests/nginx-tests/cases/variable.t .................... ok
All tests successful.
Files=19, Tests=511, 193 wallclock secs ( 0.22 usr  0.06 sys + 48.87 cusr  7.77 csys = 56.92 CPU)
Result: PASS

$ cat dtest.sh
nginx_src=$(pwd)
nginx_bin=$nginx_src/objs/nginx
nginx_test_lib=$nginx_src/tests/nginx-tests/nginx-tests/lib
nginx_case=tests/nginx-tests/nginx-tests

if [ "$1" != "" ]; then
  nginx_case=$1
fi

TEST_NGINX_BINARY="$nginx_bin" prove -I $nginx_test_lib $nginx_case
```

**Comment by chobits** [comment]
Thanks, merged!

**Pull request merged**
