### PR TITLE
modules/ngx_http_upstream_keepalive_module: checked conflict with off…

### PR DESCRIPTION
**Pull request by chobits**

### CODE REVIEW

**Comment by chobits** [comment]
```
$ ./configure --add-dynamic-module=modules/ngx_http_upstream_keepalive_module/
....
./configure: error: must disable nginx offical module with "--without-http_upstream_keepalive_module" option
```

**Comment by chobits** [comment]
try to fix https://github.com/alibaba/tengine/issues/1203

**Comment by wangfakang** [comment]
ACK.

**Comment by yunoasgit** [comment]
https://github.com/alibaba/tengine/issues/1203

Thank you very much for your strong support.
tengine2.3.0  selfless dedication

@wangfakang  @chobits

**Pull request merged**
