### PR TITLE
HTTP/2: porting from nginx v1.9.x

### PR DESCRIPTION
**Pull request by PeterDaveHello**
from nginx 1.9.5~1.9.7

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
oops ...

**Comment by chobits** [comment]
hi @PeterDaveHello 
Could you run nginx http/2 test case [h2.t](http://hg.nginx.org/nginx-tests/file/bc4d6e2bd031/h2.t)?

You can use the following command:
```
TEST_NGINX_BINARY=/path/to/sbin/tengine prove -v -I /path/to/nginx-tests/lib /path/to/nginx-tests/h2.t
```

**Comment by PeterDaveHello** [comment]
sure

**Comment by PeterDaveHello** [comment]
hmmmm ... any idea to enable shmem?
```
1..0 # SKIP shmem not compiled in
skipped: shmem not compiled in
Files=1, Tests=0,  1 wallclock secs ( 0.01 usr  0.00 sys +  0.08 cusr  0.02 csys =  0.11 CPU)
Result: NOTESTS
```

**Comment by PeterDaveHello** [comment]
Picture first:

[http2-and-spdy-indicator](https://chrome.google.com/webstore/detail/http2-and-spdy-indicator/mpbpobfflnpcgagjijhmgnchggcjblin)
screenshot from 2015-10-02 00 23 00
[chrome://net-internals/#http2](chrome://net-internals/#http2)
screenshot from 2015-10-02 00 23 03

**Comment by PeterDaveHello** [comment]
test log out:

```
#   Failed test 'weight - PRIORITY 1'
#   at /home/peter/works/nginx-tests/h2.t line 1550.
#          got: '3 1 1'
#     expected: '3 1'

#   Failed test 'weight - PRIORITY 2'
#   at /home/peter/works/nginx-tests/h2.t line 1574.
#          got: '1 1 3'
#     expected: '1 3'

#   Failed test 'weight - HEADERS PRIORITY 1'
#   at /home/peter/works/nginx-tests/h2.t line 1596.
#          got: '3 1 1'
#     expected: '3 1'

#   Failed test 'weight - HEADERS PRIORITY 2'
#   at /home/peter/works/nginx-tests/h2.t line 1618.
#          got: '1 1 3'
#     expected: '1 3'

#   Failed test 'dependency - PRIORITY 1'
#   at /home/peter/works/nginx-tests/h2.t line 1646.
#          got: '3 1 1'
#     expected: '3 1'

#   Failed test 'dependency - PRIORITY 2'
#   at /home/peter/works/nginx-tests/h2.t line 1672.
#          got: '1 1 3'
#     expected: '1 3'

#   Failed test 'dependency - HEADERS PRIORITY 1'
#   at /home/peter/works/nginx-tests/h2.t line 1698.
#          got: '3 1 1'
#     expected: '3 1'

#   Failed test 'dependency - HEADERS PRIORITY 2'
#   at /home/peter/works/nginx-tests/h2.t line 1724.
#          got: '1 1 3'
#     expected: '1 3'

#   Failed test 'weighted dependency - PRIORITY 1'
#   at /home/peter/works/nginx-tests/h2.t line 1756.
#          got: '5 1 1 3'
#     expected: '5 1 3'

#   Failed test 'weighted dependency - PRIORITY 2'
#   at /home/peter/works/nginx-tests/h2.t line 1788.
#          got: '5 3 1 1'
#     expected: '5 3 1'
# Looks like you failed 10 tests of 211.
/home/peter/works/nginx-tests/h2.t .. 
1..211
ok 1 - WINDOW_UPDATE frame
ok 2 - WINDOW_UPDATE zero flags
ok 3 - WINDOW_UPDATE zero sid
ok 4 - WINDOW_UPDATE fixed length
ok 5 - SETTINGS frame
ok 6 - SETTINGS flags
ok 7 - SETTINGS stream
ok 8 - SETTINGS frame ack
ok 9 - SETTINGS flags ack
ok 10 - PING frame
ok 11 - PING payload
ok 12 - PING flags ack
ok 13 - PING stream
ok 14 - recv timeout - new connection GOAWAY
ok 15 - recv timeout - new connection code
ok 16 - recv timeout - idle connection GOAWAY
ok 17 - idle timeout - new connection GOAWAY
ok 18 - idle timeout - idle connection GOAWAY
ok 19 - idle timeout - idle connection code
ok 20 - HEADERS frame
ok 21 - HEADERS stream
ok 22 - HEADERS status
ok 23 - HEADERS header
ok 24 - DATA frame
ok 25 - DATA length
ok 26 - DATA payload
ok 27 - HEADERS stream 2
ok 28 - HEADERS status 2
ok 29 - HEADERS header 2
ok 30 - DATA frame 2
ok 31 - HEADERS stream 2
ok 32 - DATA length 2
ok 33 - DATA payload 2
ok 34 - indexed header field
ok 35 - literal with indexing
ok 36 - literal with indexing - huffman
ok 37 - literal with indexing - new
ok 38 - literal with indexing - new huffman
ok 39 - literal without indexing
ok 40 - literal without indexing - huffman
ok 41 - literal without indexing - new
ok 42 - literal without indexing - new huffman
ok 43 - literal never indexed
ok 44 - literal never indexed - huffman
ok 45 - literal never indexed - new
ok 46 - literal never indexed - new huffman
ok 47 - value with indexing - new
ok 48 - value with indexing - indexed
ok 49 - name with indexing - new
ok 50 - name with indexing - indexed
ok 51 - updated table size - remaining index
ok 52 - invalid index
ok 53 - invalid index - GOAWAY
ok 54 - invalid index - GOAWAY last stream
ok 55 - invalid index - GOAWAY COMPRESSION_ERROR
ok 56 - HEAD - HEADERS
ok 57 - HEAD - HEADERS status
ok 58 - HEAD - HEADERS header
ok 59 - HEAD - no body
ok 60 - PROXY HEADERS frame
ok 61 - PROXY remote addr
ok 62 - range - HEADERS status
ok 63 - range - DATA length
ok 64 - range - DATA payload
ok 65 - http variable - h2c
ok 66 - http variable - npn
ok 67 # skip OpenSSL ALPN support required
ok 68 - server_protocol variable
ok 69 - server_protocol variable - npn
ok 70 # skip OpenSSL ALPN support required
ok 71 - scheme variable
ok 72 - scheme variable - npn
ok 73 # skip OpenSSL ALPN support required
ok 74 - https variable
ok 75 - https variable - npn
ok 76 # skip OpenSSL ALPN support required
ok 77 - chunk_size frames
ok 78 - chunk_size data
ok 79 - chunk_size flags
ok 80 - CONTINUATION - fragment 1
ok 81 - CONTINUATION - fragment 2
ok 82 - CONTINUATION - fragment 3
ok 83 - CONTINUATION - in header field
ok 84 - padding - HEADERS status
ok 85 - padding - next stream
ok 86 - multiple request header fields - cookie
ok 87 - multiple request header fields - cookie 2
ok 88 - multiple request header fields - semi-colon
ok 89 - multiple request header fields proxied - semi-colon
ok 90 - multiple request header fields proxied - dublicate cookie
ok 91 - multiple request header fields proxied - cookie 1
ok 92 - multiple request header fields proxied - cookie 2
ok 93 - multiple response header fields - cookie
ok 94 - multiple response header fields - cookie 2
ok 95 - multiple response header proxied - cookie
ok 96 - multiple response header proxied - cookie 2
ok 97 - multiple response header proxied - upstream cookie
ok 98 - multiple response header proxied - upstream cookie 2
ok 99 - redirect - HEADERS
ok 100 - redirect - DATA
ok 101 - redirect - DATA payload
ok 102 - return 301 absolute - status
ok 103 - return 301 absolute - location
ok 104 - return 301 relative - status
ok 105 - return 301 relative - location
ok 106 - return 301 relative - authority - status
ok 107 - return 301 relative - authority - location
ok 108 - return 301 relative - host - status
ok 109 - return 301 relative - host - location
ok 110 - virtual host - host - status
ok 111 - virtual host - host - DATA
ok 112 - virtual host - authority - status
ok 113 - virtual host - authority - DATA
ok 114 - virtual host 2 - host - status
ok 115 - virtual host 2 - host - DATA
ok 116 - virtual host 2 - authority - status
ok 117 - virtual host 2 - authority - DATA
ok 118 - gzip - encoding
ok 119 - gzip - DATA
ok 120 - proxy cache
ok 121 - proxy cache - DATA
ok 122 - proxy cache - DATA payload
ok 123 - proxy cache conditional
ok 124 - proxy cache HEAD - no body
ok 125 - proxy cache HEAD buffering off - no body
ok 126 - request body
ok 127 - request body with padding
ok 128 - request body with padding - next
ok 129 - iws - stream blocked on initial window size
ok 130 - iws - PING not blocked
ok 131 - iws - updated stream window
ok 132 - iws - updated connection window
ok 133 - iws - increased
ok 134 - negative window - SETTINGS frame ack
ok 135 - negative window - SETTINGS flags ack
ok 136 - negative window - no data
ok 137 - zero window - no data
ok 138 - positive window
ok 139 - positive window - data
ok 140 - positive window - data length
ok 141 - large response - HEADERS
ok 142 - large response - DATA
ok 143 - max frame size - default
ok 144 - max frame size - custom
ok 145 - response CONTINUATION - headers
ok 146 - response CONTINUATION - header 1
ok 147 - response CONTINUATION - header 2
ok 148 - response CONTINUATION - header 3
ok 149 - response CONTINUATION - max frame size
ok 150 - no body CONTINUATION - headers
ok 151 - no body CONTINUATION - header 1
ok 152 - no body CONTINUATION - header 2
ok 153 - no body CONTINUATION - header 3
ok 154 - no body CONTINUATION - max frame size
not ok 155 - response header frames limited # TODO not yet
#   Failed (TODO) test 'response header frames limited'
#   at /home/peter/works/nginx-tests/h2.t line 1355.
#     '98358'
#         <=
#     '16384'
ok 156 - field size less
ok 157 - field size second
ok 158 - field size equal
ok 159 - field size greater
ok 160 - header size less
ok 161 - header size second
ok 162 - header size equal
ok 163 - header size greater
ok 164 - header size new index
ok 165 - header size indexed
ok 166 - header size indexed greater
ok 167 - multiple - stream1 data
ok 168 - multiple - stream2 no data
ok 169 - multiple - stream1 remain data
ok 170 - multiple - stream2 full data
not ok 171 - weight - PRIORITY 1
not ok 172 - weight - PRIORITY 2
not ok 173 - weight - HEADERS PRIORITY 1
not ok 174 - weight - HEADERS PRIORITY 2
not ok 175 - dependency - PRIORITY 1
not ok 176 - dependency - PRIORITY 2
not ok 177 - dependency - HEADERS PRIORITY 1
not ok 178 - dependency - HEADERS PRIORITY 2
not ok 179 - weighted dependency - PRIORITY 1
not ok 180 - weighted dependency - PRIORITY 2
ok 181 - limit_conn first stream
ok 182 - limit_conn rejected
ok 183 - RST_STREAM 1
ok 184 - RST_STREAM 2
ok 185 - http2_max_concurrent_streams SETTINGS
ok 186 - http2_max_concurrent_streams
ok 187 - http2_max_concurrent_streams 2
ok 188 - http2_max_concurrent_streams RST_STREAM sid
ok 189 - http2_max_concurrent_streams RST_STREAM length
ok 190 - http2_max_concurrent_streams RST_STREAM flags
ok 191 - http2_max_concurrent_streams RST_STREAM code
ok 192 - http2_max_concurrent_streams 3
ok 193 - newline in request header
ok 194 - newline in request header - RST_STREAM sid
ok 195 - newline in request header - RST_STREAM length
ok 196 - newline in request header - RST_STREAM flags
ok 197 - newline in request header - RST_STREAM code
ok 198 - even stream - GOAWAY frame
ok 199 - even stream - error code
ok 200 - even stream - last stream
ok 201 - backward stream - GOAWAY frame
ok 202 - backward stream - error code
ok 203 - backward stream - last stream
ok 204 - dup stream - GOAWAY frame
ok 205 - dup stream - error code
ok 206 - dup stream - last stream
not ok 207 - incomplete headers # TODO not yet
#   Failed (TODO) test 'incomplete headers'
#   at /home/peter/works/nginx-tests/h2.t line 1998.
#          got: '200'
#     expected: '400'
ok 208 - empty authority
ok 209 - unknown frame type
ok 210 - GOAWAY on connection close
ok 211 - no alerts # TODO alerts
Dubious, test returned 10 (wstat 2560, 0xa00)
Failed 10/211 subtests 
	(less 4 skipped subtests: 197 okay)
	(1 TODO test unexpectedly succeeded)

Test Summary Report
-------------------
/home/peter/works/nginx-tests/h2.t (Wstat: 2560 Tests: 211 Failed: 10)
  Failed tests:  171-180
  TODO passed:   211
  Non-zero exit status: 10
Files=1, Tests=211, 17 wallclock secs ( 0.05 usr  0.00 sys +  0.55 cusr  0.16 csys =  0.76 CPU)
Result: FAIL
```

We have some bugs on PRIORITY issue .

**Comment by cfsego** [comment]
Thank you for your patching. And test cases all passed now?

**Comment by PeterDaveHello** [comment]
Nope, not yet, some tests of the priority cases have some problem, and I am not familiar with the codes (as above), just apply the patches and fix the conflicts, may needs help from others ...

**Comment by cfsego** [comment]
thank you for your prepared work, and we will do it together from now on.

**Comment by PeterDaveHello** [comment]
Thanks @cfsego , I think I should study C hared and also learn some perl from now on, ha.

**Comment by cfsego** [comment]
I found your ngx_http_v2_state_field_len is different from nginx 1.9.6/1.9.5
If you have missed something?

**Comment by PeterDaveHello** [comment]
> I found your ngx_http_v2_state_field_len is different from nginx 1.9.6/1.9.5
If you have missed something?

I'll take a look at it today.

**Comment by PeterDaveHello** [comment]
@cfsego I didn't find the difference of ngx_http_v2_state_field_len, would you mind to point me out?

**Comment by PeterDaveHello** [comment]
btw this PR contains the http/2.0 commits from nginx v1.9.5~1.9.7

**Comment by wangfakang** [comment]
@PeterDaveHello  That's a great pr, en  you have been in the online environment?  and have problem ?
THX.

**Comment by PeterDaveHello** [comment]
@wangbin579 I have no problem yet, but I can not guarantee ...

**Comment by cfsego** [comment]
en, the 'h2scf' structure occurred in nginx 1.9.7.

**Comment by PeterDaveHello** [comment]
okay, thanks, I'll find it out.

**Comment by PeterDaveHello** [comment]
@cfsego do you mean this part:
```diff
<     pos = ngx_proxy_protocol_parse(h2c->connection, pos, end);
---
>     pos = ngx_proxy_protocol_read(h2c->connection, pos, end);
```

This is because the difference between nginx and tengine, and it's the only part not the same with upstream, tengine uses ngx_proxy_protocol_parse, nginx uses ngx_proxy_protocol_read, there are some differences between these two functions, maybe this is the problem.

**Comment by cfsego** [comment]
and it is ok, because they are just of different names.

I found something reasonable.
I printed the length of each frame out, and it was like this:

8192 8192 8192 8192 8192 8192 8192 8191 at h2b.t line 334.
1 80 at h2b.t line 340.

em, very strange.

so I believe it is something wrong with flow-control or buffer-split.

**Comment by cfsego** [comment]
It is OK, for the two functions is just of different names.

I printed the length of each response frames out, and found something reasonable.
Of nginx:
>8192 8192 8192 8192 8192 8192 8192 8191 at h2.t line 2543.
>81 at h2.t line 2555.

Of tengine:
>8192 8192 8192 8192 8192 8192 8192 8191 at h2.t line 2543.
>1 80 at h2.t line 2555.

So, I think there may be something wrong with flow-control or output buffer-split.

**Comment by cfsego** [comment]
This is the patch.
https://github.com/cfsego/tengine/commit/debe4135f3c48e7e83385033320e8539e2214102

**Comment by PeterDaveHello** [comment]
hm, @cfsego, may I cherry-pick your patch? Thanks

**Comment by cfsego** [comment]
of course

**Comment by cfsego** [comment]
And I am grateful if you recover spdy, because a pure http v2 web server is less useful for now.

**Comment by PeterDaveHello** [comment]
@cfsego thanks, picked it up without and changes, I think we can try the spdy later, the modern browsers is moving on http/2.0, http://caniuse.com/#feat=http2 most of them support it, only mobile devices need much more time.

**Comment by cfsego** [comment]
because each visitor of alibaba should be ok, otherwise, we will suffer loss.
thank you

**Comment by PeterDaveHello** [comment]
here comes the new test result:
```
Use of uninitialized value $1 in split at lib/Test/Nginx.pm line 190.
Use of uninitialized value $1 in split at lib/Test/Nginx.pm line 190.
Use of uninitialized value $1 in split at lib/Test/Nginx.pm line 190.
/home/peter/repos/nginx-tests/h2.t .. 
1..292
ok 1 # skip no Upgrade-based negotiation
ok 2 # skip no Upgrade-based negotiation
ok 3 - WINDOW_UPDATE frame
ok 4 - WINDOW_UPDATE zero flags
ok 5 - WINDOW_UPDATE zero sid
ok 6 - WINDOW_UPDATE fixed length
ok 7 - SETTINGS frame
ok 8 - SETTINGS flags
ok 9 - SETTINGS stream
ok 10 - SETTINGS frame ack
ok 11 - SETTINGS flags ack
ok 12 - PING frame
ok 13 - PING payload
ok 14 - PING flags ack
ok 15 - PING stream
ok 16 - recv timeout - new connection GOAWAY
ok 17 - recv timeout - new connection code
ok 18 - recv timeout - idle connection GOAWAY
ok 19 - idle timeout - new connection GOAWAY
ok 20 - idle timeout - idle connection GOAWAY
ok 21 - idle timeout - idle connection code
ok 22 - GOAWAY invalid length - GOAWAY frame
ok 23 - GOAWAY invalid length - GOAWAY FRAME_SIZE_ERROR
not ok 24 - GOAWAY invalid stream - GOAWAY frame # TODO not yet
#   Failed (TODO) test 'GOAWAY invalid stream - GOAWAY frame'
#   at /home/peter/repos/nginx-tests/h2.t line 418.
not ok 25 - GOAWAY invalid stream - GOAWAY PROTOCOL_ERROR # TODO not yet
#   Failed (TODO) test 'GOAWAY invalid stream - GOAWAY PROTOCOL_ERROR'
#   at /home/peter/repos/nginx-tests/h2.t line 419.
#          got: undef
#     expected: '1'
ok 26 - client-initiated PUSH_PROMISE - GOAWAY frame
ok 27 - client-initiated PUSH_PROMISE - GOAWAY PROTOCOL_ERROR
ok 28 - HEADERS frame
ok 29 - HEADERS stream
ok 30 - HEADERS status
ok 31 - HEADERS header
ok 32 - DATA frame
ok 33 - DATA length
ok 34 - DATA payload
ok 35 - HEADERS stream 2
ok 36 - HEADERS status 2
ok 37 - HEADERS header 2
ok 38 - DATA frame 2
ok 39 - HEADERS stream 2
ok 40 - DATA length 2
ok 41 - DATA payload 2
ok 42 - indexed header field
ok 43 - literal with indexing
ok 44 - literal with indexing - huffman
ok 45 - literal with indexing - new
ok 46 - literal with indexing - new huffman
ok 47 - literal without indexing
ok 48 - literal without indexing - huffman
ok 49 - literal without indexing - multibyte index
ok 50 - literal without indexing - multibyte index value
ok 51 - literal without indexing - new
ok 52 - literal without indexing - new huffman
ok 53 - literal never indexed
ok 54 - literal never indexed - huffman
ok 55 - literal never indexed - multibyte index
ok 56 - literal never indexed - multibyte index value
ok 57 - literal never indexed - new
ok 58 - literal never indexed - new huffman
ok 59 - value with indexing - new
ok 60 - value with indexing - indexed
ok 61 - name with indexing - new
ok 62 - name with indexing - indexed
ok 63 - name with indexing - indexed name
ok 64 - updated table size - remaining index
ok 65 - invalid index
ok 66 - invalid index - GOAWAY
ok 67 - invalid index - GOAWAY last stream
ok 68 - invalid index - GOAWAY COMPRESSION_ERROR
ok 69 - zero index - GOAWAY
ok 70 - zero index - GOAWAY COMPRESSION_ERROR
ok 71 - invalid table size - GOAWAY
ok 72 - invalid table size - GOAWAY last stream
ok 73 - invalid table size - GOAWAY COMPRESSION_ERROR
ok 74 - HEAD - HEADERS
ok 75 - HEAD - HEADERS status
ok 76 - HEAD - HEADERS header
ok 77 - HEAD - no body
ok 78 - PROXY HEADERS frame
ok 79 - PROXY remote addr
ok 80 - range - HEADERS status
ok 81 - range - DATA length
ok 82 - range - DATA payload
ok 83 - http variable - h2c
ok 84 - http variable - npn
ok 85 # skip OpenSSL ALPN support required
ok 86 - server_protocol variable
ok 87 - server_protocol variable - npn
ok 88 # skip OpenSSL ALPN support required
ok 89 - scheme variable
ok 90 - scheme variable - npn
ok 91 # skip OpenSSL ALPN support required
ok 92 - https variable
ok 93 - https variable - npn
ok 94 # skip OpenSSL ALPN support required
ok 95 - chunk_size frames
ok 96 - chunk_size data
ok 97 - chunk_size flags
ok 98 - CONTINUATION - fragment 1
ok 99 - CONTINUATION - fragment 2
ok 100 - CONTINUATION - fragment 3
ok 101 - CONTINUATION - in header field
ok 102 - GOAWAY - CONTINUATION closed stream
ok 103 - GOAWAY - CONTINUATION closed stream - PROTOCOL_ERROR
ok 104 - padding - HEADERS status
ok 105 - padding - next stream
ok 106 - multiple request header fields - cookie
ok 107 - multiple request header fields - cookie 2
ok 108 - multiple request header fields - semi-colon
ok 109 - multiple request header fields proxied - semi-colon
ok 110 - multiple request header fields proxied - dublicate cookie
ok 111 - multiple request header fields proxied - cookie 1
ok 112 - multiple request header fields proxied - cookie 2
ok 113 - multiple response header fields - cookie
ok 114 - multiple response header fields - cookie 2
ok 115 - multiple response header proxied - cookie
ok 116 - multiple response header proxied - cookie 2
ok 117 - multiple response header proxied - upstream cookie
ok 118 - multiple response header proxied - upstream cookie 2
ok 119 - redirect - HEADERS
ok 120 - redirect - DATA
ok 121 - redirect - DATA payload
ok 122 - return 301 absolute - status
ok 123 - return 301 absolute - location
ok 124 - return 301 relative - status
ok 125 - return 301 relative - location
ok 126 - return 301 relative - authority - status
ok 127 - return 301 relative - authority - location
ok 128 - return 301 relative - host - status
ok 129 - return 301 relative - host - location
ok 130 - virtual host - host - status
ok 131 - virtual host - host - DATA
ok 132 - virtual host - authority - status
ok 133 - virtual host - authority - DATA
ok 134 - virtual host 2 - host - status
ok 135 - virtual host 2 - host - DATA
ok 136 - virtual host 2 - authority - status
ok 137 - virtual host 2 - authority - DATA
ok 138 - gzip - encoding
ok 139 - gzip - DATA
ok 140 - proxy cache
ok 141 - proxy cache - DATA
ok 142 - proxy cache - DATA payload
ok 143 - proxy cache conditional
ok 144 - proxy cache HEAD - no body
not ok 145 - proxy cache write - data frames # TODO not yet
#   Failed (TODO) test 'proxy cache write - data frames'
#   at /home/peter/repos/nginx-tests/h2.t line 1359.
#          got: '2'
#     expected: '1'
not ok 146 - proxy cache write - data # TODO not yet

#   Failed (TODO) test 'proxy cache write - data'
#   at /home/peter/repos/nginx-tests/h2.t line 1360.
#          got: 'SEE-THIS '
#     expected: 'SEE-THIS'
not ok 147 - proxy cache write - flags # TODO not yet

#   Failed (TODO) test 'proxy cache write - flags'
#   at /home/peter/repos/nginx-tests/h2.t line 1361.
#          got: '0 1'
#     expected: '1'
ok 148 - proxy cache HEAD buffering off - no body
ok 149 - request body
ok 150 - request body with padding
ok 151 - request body with padding - next
ok 152 - request body in multiple frames
ok 153 - request body - limit req
ok 154 # skip leaves coredump
ok 155 - request body less than content-length
ok 156 - request body more than content-length
ok 157 - client_max_body_size - status
ok 158 - client_max_body_size - body
ok 159 - client_max_body_size - limited
ok 160 - client_max_body_size many - status
ok 161 - client_max_body_size many - body
ok 162 - client_max_body_size many - limited
ok 163 - client_max_body_size pad - status
ok 164 - client_max_body_size pad - body
ok 165 - client_max_body_size pad - limited
ok 166 - client_max_body_size many pad - status
ok 167 - client_max_body_size many pad - body
ok 168 - client_max_body_size many pad - limited
ok 169 - request body without content-length - status
ok 170 - request body without content-length - body
ok 171 - request body without content-length - limited
ok 172 - request body without content-length many - status
ok 173 - request body without content-length many - body
ok 174 - request body without content-length many - limited
ok 175 - request body without content-length pad - status
ok 176 - request body without content-length pad - body
ok 177 - request body without content-length pad - limited
ok 178 - request body without content-length many pad - status
ok 179 - request body without content-length many pad - body
ok 180 - request body without content-length many pad - limited
ok 181 - iws - stream blocked on initial window size
ok 182 - iws - PING not blocked
ok 183 - iws - updated stream window
ok 184 - iws - updated connection window
ok 185 - iws - increased
ok 186 - negative window - SETTINGS frame ack
ok 187 - negative window - SETTINGS flags ack
ok 188 - negative window - no data
ok 189 - zero window - no data
ok 190 - positive window
ok 191 - positive window - data
ok 192 - positive window - data length
ok 193 - large response - HEADERS
ok 194 - large response - DATA
ok 195 - large response - send timeout
ok 196 - large response - queued with RST_STREAM
ok 197 - max frame size - default
ok 198 - max frame size - custom
ok 199 - response CONTINUATION - headers
ok 200 - response CONTINUATION - header 1
ok 201 - response CONTINUATION - header 2
ok 202 - response CONTINUATION - header 3
ok 203 - response CONTINUATION - max frame size
ok 204 - no body CONTINUATION - headers
ok 205 - no body CONTINUATION - header 1
ok 206 - no body CONTINUATION - header 2
ok 207 - no body CONTINUATION - header 3
ok 208 - no body CONTINUATION - max frame size
ok 209 - response header frames limited
ok 210 - response header - parts # TODO not yet
ok 211 - response header - headers # TODO not yet
ok 212 - response header split - parts # TODO not yet
ok 213 - field name size less
ok 214 - field name size second
ok 215 - field name size equal
ok 216 - field name size greater
ok 217 - field value size less
ok 218 - field value size equal
ok 219 - field value size greater
ok 220 - header size less
ok 221 - header size second
ok 222 - header size equal
ok 223 - header size greater
ok 224 - header size new index
ok 225 - header size indexed
ok 226 - header size indexed greater
ok 227 - HPACK table boundary
ok 228 - HPACK table boundary - header field name
ok 229 - HPACK table boundary - header field value
ok 230 - multiple - stream1 data
ok 231 - multiple - stream2 no data
ok 232 - multiple - stream1 remain data
ok 233 - multiple - stream2 full data
ok 234 - weight - PRIORITY 1
ok 235 - weight - PRIORITY 2
ok 236 - weight - HEADERS PRIORITY 1
ok 237 - weight - HEADERS PRIORITY 2
ok 238 - dependency - PRIORITY 1
ok 239 - dependency - PRIORITY 2
ok 240 - dependency - PRIORITY self - RST_STREAM
ok 241 - dependency - PRIORITY self - PROTOCOL_ERROR
ok 242 - dependency - HEADERS PRIORITY 1
ok 243 - dependency - HEADERS PRIORITY 2
ok 244 - dependency - HEADERS self - RST_STREAM
ok 245 - dependency - HEADERS self - PROTOCOL_ERROR
ok 246 - weighted dependency - PRIORITY 1
ok 247 - weighted dependency - PRIORITY 2
ok 248 - removed dependency
ok 249 - removed dependency - first stream
ok 250 - removed dependency - last stream
ok 251 - exclusive dependency - parent removed
ok 252 - exclusive dependency - first stream
ok 253 - exclusive dependency - last stream
ok 254 - limit_conn first stream
ok 255 - limit_conn rejected
ok 256 - RST_STREAM 1
ok 257 - RST_STREAM 2
ok 258 - http2_max_concurrent_streams SETTINGS
ok 259 - http2_max_concurrent_streams
ok 260 - http2_max_concurrent_streams 2
ok 261 - http2_max_concurrent_streams RST_STREAM sid
ok 262 - http2_max_concurrent_streams RST_STREAM length
ok 263 - http2_max_concurrent_streams RST_STREAM flags
ok 264 - http2_max_concurrent_streams RST_STREAM code
ok 265 - http2_max_concurrent_streams 3
ok 266 - invalid preface - GOAWAY frame
ok 267 - invalid preface - error code
ok 268 - invalid preface 2 - GOAWAY frame
ok 269 - invalid preface 2 - error code
ok 270 - invalid PROXY - GOAWAY frame
ok 271 - invalid PROXY - error code
ok 272 - newline in request header
ok 273 - newline in request header - RST_STREAM sid
ok 274 - newline in request header - RST_STREAM length
ok 275 - newline in request header - RST_STREAM flags
ok 276 - newline in request header - RST_STREAM code
ok 277 - after invalid header name # TODO not yet
ok 278 - even stream - GOAWAY frame
ok 279 - even stream - error code
ok 280 - even stream - last stream
ok 281 - backward stream - GOAWAY frame
ok 282 - backward stream - error code
ok 283 - backward stream - last stream
ok 284 - dup stream - GOAWAY frame
ok 285 - dup stream - error code
ok 286 - dup stream - last stream
not ok 287 - incomplete headers # TODO not yet
#   Failed (TODO) test 'incomplete headers'
#   at /home/peter/repos/nginx-tests/h2.t line 2831.
#          got: '200'
#     expected: '400'
ok 288 - empty authority
ok 289 - unknown frame type
ok 290 - invalid path
ok 291 - GOAWAY on connection close
not ok 292 - no alerts # TODO alerts
#   Failed (TODO) test 'no alerts'
#   at lib/Test/Nginx.pm line 70.
#          got: '2015/12/02 17:50:46 [alert] 21977#0: *173 open socket #22 left in connection 14
# 2015/12/02 17:50:46 [alert] 21977#0: *174 open socket #27 left in connection 15
# 2015/12/02 17:50:46 [alert] 21977#0: *175 open socket #29 left in connection 16
# 2015/12/02 17:50:46 [alert] 21977#0: aborting'
#     expected: ''
ok
All tests successful.

Test Summary Report
-------------------
/home/peter/repos/nginx-tests/h2.t (Wstat: 0 Tests: 292 Failed: 0)
  TODO passed:   210-212, 277
Files=1, Tests=292, 21 wallclock secs ( 0.06 usr  0.00 sys +  0.77 cusr  0.16 csys =  0.99 CPU)
Result: PASS
```

**Comment by PeterDaveHello** [comment]
Looks okay now!

**Comment by cfsego** [comment]
why you close and reopen?

**Comment by PeterDaveHello** [comment]
@cfsego that's a mistake, didn't change anything :) Are we good to go now?

**Comment by squarepants** [comment]
@PeterDaveHello how do I use it ? can I get some fully cover instruction here, I'm new to Tengine, so far I can only get tengine up and running, when I add "http2" parameter to my config, it says 
`nginx: [emerg] invalid parameter "http2" in /usr/local/nginx/conf/nginx.conf:14`

**Comment by PeterDaveHello** [comment]
@squarepants do you complie from latest source?

**Comment by squarepants** [comment]
I tried your branch and it says 
```
$ ./configure --enable-mods-static=all --with-ipv6 --with-http_v2_module
./configure: error: invalid option "--with-http_v2_module"
```
BTW, It's this the same implementation in nginx 1.9.5 ?

**Comment by PeterDaveHello** [comment]
I have no this problem, would you please confirm that your HEAD is at f708a2b? Thanks.

**Comment by cfsego** [comment]
I found a http2_new in your repository, what's that?

**Comment by PeterDaveHello** [comment]
@cfsego it's nothing, no mind.

**Comment by cfsego** [comment]
@PeterDaveHello 
I think you should convert all 'HTTP_HTTP2' to 'HTTP_V2' in your respository, and it will then be OK to merge

**Comment by cfsego** [comment]
I have made a branch 2.1.2, merged http/2 and restore

**Comment by PeterDaveHello** [comment]
Oh nice :+1:

**Comment by PeterDaveHello** [comment]
```diff
diff --git a/auto/options b/auto/options
index 472fef8..8860b06 100644
--- a/auto/options
+++ b/auto/options
@@ -1071,7 +1071,7 @@ if [ $NGX_SHARED_ALL_MODULES = YES ]; then
     HTTP_REQ_STATUS=NO

 elif [ $NGX_STATIC_ALL_MODULES = YES ]; then
-    HTTP_HTTP2=YES
+    HTTP_V2=YES
     HTTP_CACHE=YES
     HTTP_CHARSET=YES
     HTTP_GZIP=YES
diff --git a/src/http/modules/ngx_http_ssl_module.c b/src/http/modules/ngx_http_ssl_module.c
index 0e2b215..6d35528 100644
--- a/src/http/modules/ngx_http_ssl_module.c
+++ b/src/http/modules/ngx_http_ssl_module.c
@@ -9,7 +9,7 @@
 #include <ngx_core.h>
 #include <ngx_http.h>

-#if (NGX_HTTP_HTTP2)
+#if (NGX_HTTP_V2)
 #include <v2/ngx_http_v2_module.h>
 #endif
```

**Comment by PeterDaveHello** [comment]
Test Summary Report
-------------------
/home/peter/repos/nginx-tests/h2.t (Wstat: 0 Tests: 292 Failed: 0)
  TODO passed:   210-212, 277
Files=1, Tests=292, 20 wallclock secs ( 0.07 usr  0.00 sys +  0.67 cusr  0.14 csys =  0.88 CPU)
Result: PASS

**Comment by cfsego** [comment]
nice

**Comment by leeweir** [comment]
nice job

**Pull request merged**
