### PR TITLE
updated modules from nginx-1.15.1

### PR DESCRIPTION
**Pull request by chobits**
# updated module from nginx-1.15.1

* addtion filter module
* dav module
* browser module
* fastcgi module
* geo module
* scgi module
* headers filter module
* realip module
* memcached module

# updated module from nginx-1.15.2

Some test cases need nginx-1.15.2.

* ssl module (from nginx-1.15.2)
* perl module (from nginx-1.15.2)
* log module (from nginx-1.15.2)
* rewrite module

# updated test cases 

cases from latest nginx-tests hg repo

* sub_filter*.t
* addtion*.t
* dav*.t
* fastcgi*.t
* geo*.t
* headers.t
* scgi*.t
* realip*.t
* memcached*.t
* ssl*.t
* perl*.t
* \*log*.t
* rewrite*.t

# not updated module, for next pull request

* limit_req: tengine has its own function
* image filter: tengine has its own function

### CODE REVIEW

**Comment by chobits** [comment]
# Test Case for sub*.t & addtion*.t

* Tested-by: Xiaochen Wang 
* Date: Wed Jan 30 12:49:06 CST 2019
* pwd: /home/xiaochen.wxc/work/github/tengine-xiaochen
* cases: `
../nginx-tests/sub*.t ../nginx-tests/addition*.t
`
* git log:

```
commit 9156923d8b0c860087a97ebb9388819856afaa2b (HEAD -> 2.3.0_update_module, origin/2.3.0_update_module)
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Wed Jan 30 12:39:38 2019 +0800

    updated test cases: sub*.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib ../nginx-tests/sub_filter_buffering.t ../nginx-tests/sub_filter_merge.t ../nginx-tests/sub_filter_multi2.t ../nginx-tests/sub_filter_multi.t ../nginx-tests/sub_filter_perl.t ../nginx-tests/sub_filter_slice.t ../nginx-tests/sub_filter_ssi.t ../nginx-tests/sub_filter.t ../nginx-tests/subrequest_output_buffer_size.t ../nginx-tests/addition_buffered.t ../nginx-tests/addition.t
../nginx-tests/sub_filter_buffering.t ........... ok
../nginx-tests/sub_filter_merge.t ............... ok
../nginx-tests/sub_filter_multi2.t .............. ok
../nginx-tests/sub_filter_multi.t ............... ok
../nginx-tests/sub_filter_perl.t ................ ok
../nginx-tests/sub_filter_slice.t ............... ok
../nginx-tests/sub_filter_ssi.t ................. ok
../nginx-tests/sub_filter.t ..................... ok
../nginx-tests/subrequest_output_buffer_size.t .. ok
../nginx-tests/addition_buffered.t .............. ok
../nginx-tests/addition.t ....................... ok
All tests successful.
Files=11, Tests=145, 52 wallclock secs ( 0.09 usr  0.03 sys +  2.09 cusr  1.28 csys =  3.49 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang xiaochen
* Date: Mon Feb  4 19:33:30 CST 2019
* hostname: e100069206110.zmf
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/dav*.t`
* git log:

```
commit ab4a28f654c8c07773b7dbc53d9112fdb5a119f5
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Mon Feb 4 19:29:40 2019 +0800

    updated test cases: dav*.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/dav_chunked.t tests/nginx-tests/nginx-tests/dav.t
tests/nginx-tests/nginx-tests/dav_chunked.t .. ok
Use of uninitialized value $1 in split at lib/Test/Nginx.pm line 259.
tests/nginx-tests/nginx-tests/dav.t .......... ok
All tests successful.
Files=2, Tests=30,  1 wallclock secs ( 0.04 usr  0.00 sys +  0.31 cusr  0.10 csys =  0.45 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang xiaochen
* Date: Mon Feb  4 20:04:23 CST 2019
* hostname: e100069206110.zmf
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/fastcgi*.t`
* git log:

```
commit 4b2adfc45008f20515a4bd6b564bb9d5d2ab2a46
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Mon Feb 4 20:03:51 2019 +0800

    updated test cases: fastcgi*.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/fastcgi_body2.t tests/nginx-tests/nginx-tests/fastcgi_body.t tests/nginx-tests/nginx-tests/fastcgi_buffering.t tests/nginx-tests/nginx-tests/fastcgi_cache.t tests/nginx-tests/nginx-tests/fastcgi_header_params.t tests/nginx-tests/nginx-tests/fastcgi_keepalive.t tests/nginx-tests/nginx-tests/fastcgi_merge_params2.t tests/nginx-tests/nginx-tests/fastcgi_merge_params.t tests/nginx-tests/nginx-tests/fastcgi_request_buffering_chunked.t tests/nginx-tests/nginx-tests/fastcgi_request_buffering.t tests/nginx-tests/nginx-tests/fastcgi_split.t tests/nginx-tests/nginx-tests/fastcgi.t tests/nginx-tests/nginx-tests/fastcgi_unix.t tests/nginx-tests/nginx-tests/fastcgi_variables.t
tests/nginx-tests/nginx-tests/fastcgi_body2.t ...................... ok
tests/nginx-tests/nginx-tests/fastcgi_body.t ....................... ok
tests/nginx-tests/nginx-tests/fastcgi_buffering.t .................. ok
tests/nginx-tests/nginx-tests/fastcgi_cache.t ...................... ok
tests/nginx-tests/nginx-tests/fastcgi_header_params.t .............. ok
tests/nginx-tests/nginx-tests/fastcgi_keepalive.t .................. ok
tests/nginx-tests/nginx-tests/fastcgi_merge_params2.t .............. ok
tests/nginx-tests/nginx-tests/fastcgi_merge_params.t ............... ok
tests/nginx-tests/nginx-tests/fastcgi_request_buffering_chunked.t .. ok
tests/nginx-tests/nginx-tests/fastcgi_request_buffering.t .......... ok
tests/nginx-tests/nginx-tests/fastcgi_split.t ...................... ok
tests/nginx-tests/nginx-tests/fastcgi.t ............................ ok
tests/nginx-tests/nginx-tests/fastcgi_unix.t ....................... ok
tests/nginx-tests/nginx-tests/fastcgi_variables.t .................. ok
All tests successful.
Files=14, Tests=113, 17 wallclock secs ( 0.08 usr  0.03 sys +  1.91 cusr  0.60 csys =  2.62 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang xiaochen
* Date: Mon Feb  4 20:05:02 CST 2019
* hostname: e100069206110.zmf
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/geo*.t`
* git log:

```
commit 4b2adfc45008f20515a4bd6b564bb9d5d2ab2a46
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Mon Feb 4 20:03:51 2019 +0800

    updated test cases: fastcgi*.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/geo_binary.t tests/nginx-tests/nginx-tests/geoip.t tests/nginx-tests/nginx-tests/geo_ipv6.t tests/nginx-tests/nginx-tests/geo.t tests/nginx-tests/nginx-tests/geo_unix.t
tests/nginx-tests/nginx-tests/geo_binary.t .. ok
tests/nginx-tests/nginx-tests/geoip.t ....... ok
tests/nginx-tests/nginx-tests/geo_ipv6.t .... ok
tests/nginx-tests/nginx-tests/geo.t ......... ok
Use of uninitialized value $1 in split at lib/Test/Nginx.pm line 259.
tests/nginx-tests/nginx-tests/geo_unix.t .... ok
All tests successful.
Files=5, Tests=63,  3 wallclock secs ( 0.05 usr  0.01 sys +  1.30 cusr  0.32 csys =  1.68 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang xiaochen
* Date: Mon Feb  4 20:31:26 CST 2019
* hostname: e100069206110.zmf
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/headers.t`
* git log:

```
commit 0a4e5c3316a77034047a871905fcecc9fb17a586
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Mon Feb 4 20:30:37 2019 +0800

    updated test cases: headers.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/headers.t
tests/nginx-tests/nginx-tests/headers.t .. ok
All tests successful.
Files=1, Tests=30,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.15 cusr  0.04 csys =  0.23 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang xiaochen
* Date: Mon Feb  4 20:31:43 CST 2019
* hostname: e100069206110.zmf
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/scgi*.t`
* git log:

```
commit 0a4e5c3316a77034047a871905fcecc9fb17a586
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Mon Feb 4 20:30:37 2019 +0800

    updated test cases: headers.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/scgi_body.t tests/nginx-tests/nginx-tests/scgi_cache.t tests/nginx-tests/nginx-tests/scgi_gzip.t tests/nginx-tests/nginx-tests/scgi_merge_params.t tests/nginx-tests/nginx-tests/scgi.t
tests/nginx-tests/nginx-tests/scgi_body.t .......... ok
tests/nginx-tests/nginx-tests/scgi_cache.t ......... ok
tests/nginx-tests/nginx-tests/scgi_gzip.t .......... ok
tests/nginx-tests/nginx-tests/scgi_merge_params.t .. ok
tests/nginx-tests/nginx-tests/scgi.t ............... ok
All tests successful.
Files=5, Tests=42,  2 wallclock secs ( 0.05 usr  0.02 sys +  0.69 cusr  0.20 csys =  0.96 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang xiaochen
* Date: Mon Feb  4 20:46:33 CST 2019
* hostname: e100069206110.zmf
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/realip*.t`
* git log:

```
commit 2eae7e80a4e91adfb86c627df4b302fd3008b182
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Mon Feb 4 20:45:50 2019 +0800

    updated test cases: realip*.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/realip_hostname.t tests/nginx-tests/nginx-tests/realip_remote_addr.t tests/nginx-tests/nginx-tests/realip_remote_port.t tests/nginx-tests/nginx-tests/realip.t
tests/nginx-tests/nginx-tests/realip_hostname.t ..... ok
tests/nginx-tests/nginx-tests/realip_remote_addr.t .. ok
tests/nginx-tests/nginx-tests/realip_remote_port.t .. ok
tests/nginx-tests/nginx-tests/realip.t .............. ok
All tests successful.
Files=4, Tests=28,  2 wallclock secs ( 0.04 usr  0.01 sys +  0.51 cusr  0.15 csys =  0.71 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang xiaochen
* Date: Tue Feb 12 16:43:54 CST 2019
* hostname: e100069206110.zmf
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/memcached*.t`
* git log:

```
commit ce01bfddc751af8059a7a2d582668e0463d7ccd4
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Tue Feb 12 16:43:04 2019 +0800

    updated test cases: memcached*.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/memcached_fake.t tests/nginx-tests/nginx-tests/memcached_keepalive_stale.t tests/nginx-tests/nginx-tests/memcached_keepalive.t tests/nginx-tests/nginx-tests/memcached.t
tests/nginx-tests/nginx-tests/memcached_fake.t ............. ok
tests/nginx-tests/nginx-tests/memcached_keepalive_stale.t .. ok
tests/nginx-tests/nginx-tests/memcached_keepalive.t ........ ok
tests/nginx-tests/nginx-tests/memcached.t .................. ok
All tests successful.
Files=4, Tests=31,  2 wallclock secs ( 0.04 usr  0.01 sys +  0.82 cusr  0.33 csys =  1.20 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang xiaochen
* Date: Tue Feb 12 20:05:16 CST 2019
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/ssl*.t`
* git log:

```
commit 124054bd5385e2d01b1288bef72a36f0db0b9244
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Tue Feb 12 20:04:03 2019 +0800

    updated test cases: ssl*.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/ssl_certificate_chain.t tests/nginx-tests/nginx-tests/ssl_certificates.t tests/nginx-tests/nginx-tests/ssl_client_escaped_cert.t tests/nginx-tests/nginx-tests/ssl_crl.t tests/nginx-tests/nginx-tests/ssl_engine_keys.t tests/nginx-tests/nginx-tests/ssl_password_file.t tests/nginx-tests/nginx-tests/ssl_proxy_protocol.t tests/nginx-tests/nginx-tests/ssl_proxy_upgrade.t tests/nginx-tests/nginx-tests/ssl_sni_reneg.t tests/nginx-tests/nginx-tests/ssl_sni_sessions.t tests/nginx-tests/nginx-tests/ssl_sni.t tests/nginx-tests/nginx-tests/ssl_stapling.t tests/nginx-tests/nginx-tests/ssl.t tests/nginx-tests/nginx-tests/ssl_verify_client.t tests/nginx-tests/nginx-tests/ssl_verify_depth.t
tests/nginx-tests/nginx-tests/ssl_certificate_chain.t .... ok
tests/nginx-tests/nginx-tests/ssl_certificates.t ......... ok
tests/nginx-tests/nginx-tests/ssl_client_escaped_cert.t .. ok
tests/nginx-tests/nginx-tests/ssl_crl.t .................. ok
which: no softhsm in (/home/xiaochen.wxc/.autojump/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/X11R6/bin:/opt/taobao/install/node.js/bin:/sbin:/bin:/usr/sbin:/usr/bin:/home/xiaochen.wxc/bin)
tests/nginx-tests/nginx-tests/ssl_engine_keys.t .......... skipped: softhsm not found
tests/nginx-tests/nginx-tests/ssl_password_file.t ........ ok
tests/nginx-tests/nginx-tests/ssl_proxy_protocol.t ....... ok
tests/nginx-tests/nginx-tests/ssl_proxy_upgrade.t ........ ok
tests/nginx-tests/nginx-tests/ssl_sni_reneg.t ............ ok
tests/nginx-tests/nginx-tests/ssl_sni_sessions.t ......... ok
tests/nginx-tests/nginx-tests/ssl_sni.t .................. ok
tests/nginx-tests/nginx-tests/ssl_stapling.t ............. ok
tests/nginx-tests/nginx-tests/ssl.t ...................... ok
tests/nginx-tests/nginx-tests/ssl_verify_client.t ........ ok
tests/nginx-tests/nginx-tests/ssl_verify_depth.t ......... ok
All tests successful.
Files=15, Tests=155, 15 wallclock secs ( 0.10 usr  0.03 sys +  4.96 cusr  1.02 csys =  6.11 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang
* Date: Tue Feb 12 20:19:40 CST 2019
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/perl*.t`
* git log:

```
commit 275ef338e87913e42d8a21135a7e3f05806093f6
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Tue Feb 12 20:18:37 2019 +0800

    updated test cases: perl*.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/perl_gzip.t tests/nginx-tests/nginx-tests/perl_sleep.t tests/nginx-tests/nginx-tests/perl_ssi.t tests/nginx-tests/nginx-tests/perl.t
tests/nginx-tests/nginx-tests/perl_gzip.t ... ok
tests/nginx-tests/nginx-tests/perl_sleep.t .. ok
tests/nginx-tests/nginx-tests/perl_ssi.t .... ok
tests/nginx-tests/nginx-tests/perl.t ........ ok
All tests successful.
Files=4, Tests=32,  2 wallclock secs ( 0.05 usr  0.01 sys +  0.67 cusr  0.16 csys =  0.89 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang
* Date: Tue Feb 12 20:34:11 CST 2019
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/*log*.t`
* git log:

```
commit 69f214b15740ee8dd7afc7cc7b31f50c5922a3ed
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Tue Feb 12 20:33:53 2019 +0800

    updated test cases: *log*.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/access_log.t tests/nginx-tests/nginx-tests/access_log_variables.t tests/nginx-tests/nginx-tests/debug_connection_syslog.t tests/nginx-tests/nginx-tests/error_log.t tests/nginx-tests/nginx-tests/mail_error_log.t tests/nginx-tests/nginx-tests/stream_access_log_escape.t tests/nginx-tests/nginx-tests/stream_access_log_none.t tests/nginx-tests/nginx-tests/stream_access_log.t tests/nginx-tests/nginx-tests/stream_error_log.t tests/nginx-tests/nginx-tests/syslog.t
tests/nginx-tests/nginx-tests/access_log.t ................ ok
tests/nginx-tests/nginx-tests/access_log_variables.t ...... ok
tests/nginx-tests/nginx-tests/debug_connection_syslog.t ... ok
tests/nginx-tests/nginx-tests/error_log.t ................. ok
tests/nginx-tests/nginx-tests/mail_error_log.t ............ ok
tests/nginx-tests/nginx-tests/stream_access_log_escape.t .. skipped: no stream available
tests/nginx-tests/nginx-tests/stream_access_log_none.t .... skipped: no stream available
tests/nginx-tests/nginx-tests/stream_access_log.t ......... skipped: no stream available
tests/nginx-tests/nginx-tests/stream_error_log.t .......... skipped: no stream available
tests/nginx-tests/nginx-tests/syslog.t .................... ok
All tests successful.
Files=10, Tests=157,  8 wallclock secs ( 0.09 usr  0.02 sys +  1.46 cusr  0.36 csys =  1.93 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by chobits** [comment]
# Test Case:
* Tested-by: Xiaochen Wang
* Date: Tue Feb 12 20:42:55 CST 2019
* pwd: /home/xiaochen/work/github/tengine-xiaochen
* cases: `tests/nginx-tests/nginx-tests/rewrite*.t`
* git log:

```
commit a75aad49d918573a5508b5bef94f3c71537e7e42
Author: Xiaochen Wang <wangxiaochen0@gmail.com>
Date:   Tue Feb 12 20:41:49 2019 +0800

    updated test cases: rewrite*.t
```

* case result:

```
$ TEST_NGINX_UNSAFE=yes TEST_NGINX_BINARY=/home/xiaochen/work/github/tengine-xiaochen/objs/nginx prove -I /home/xiaochen/work/github/tengine-xiaochen/tests/nginx-tests/nginx-tests/lib tests/nginx-tests/nginx-tests/rewrite_if.t tests/nginx-tests/nginx-tests/rewrite_set.t tests/nginx-tests/nginx-tests/rewrite.t tests/nginx-tests/nginx-tests/rewrite_unescape.t
tests/nginx-tests/nginx-tests/rewrite_if.t ........ ok
tests/nginx-tests/nginx-tests/rewrite_set.t ....... ok
Use of uninitialized value $1 in split at lib/Test/Nginx.pm line 259.
tests/nginx-tests/nginx-tests/rewrite.t ........... ok
tests/nginx-tests/nginx-tests/rewrite_unescape.t .. ok
All tests successful.
Files=4, Tests=76,  1 wallclock secs ( 0.05 usr  0.01 sys +  0.59 cusr  0.18 csys =  0.83 CPU)
Result: PASS
```

* Report-generated-by: http://github.com/chobits/tengine-script/runtest.sh

**Comment by wangfakang** [comment]
ack

**Pull request merged**
