### PR TITLE
per-vhost upstream keepalive connection cache

### PR DESCRIPTION
**Pull request by cfsego**

### CODE REVIEW

**Comment by chobits** [comment]
Some discussion for this pull request, see here: https://github.com/alibaba/tengine/issues/668.

**Comment by Dead2** [comment]
+1

**Comment by Dead2** [comment]
I'd like to mention that this keepalive implementation has been running in a production environment for about 8 months on 30+ servers with zero issues.

**Comment by chobits** [comment]
hi @Dead2 , thanks for your testing. We'll try to merge this into upstream in 2.2.1 or 2.2.2:)

**Comment by Dead2** [comment]
*nudge*

**Comment by chobits** [comment]
due in tengine-2.2.2, i am reviewing this module.

**Comment by chobits** [comment]
Ack

cc @taoyuanyuan , could u review this patch also?
Hope that we can merge this feature into tengine-2.2.2 :)

**Comment by chobits** [comment]
I have merged this module, thanks for all contirbutions.

TODO: chinese documentation, I'll add this this week.

HAPPY JESUS DAY!

**Pull request merged**
