### PR TITLE
Add test ci

### PR DESCRIPTION
**Pull request by u5surf**
We should add the test in this CI.
Although, I said in #1670, resolver_file and dynamic_resolve_aaaa still be failed.
@chobits 
Do you have any clue to resolve this issue?

### CODE REVIEW

**Comment by chobits** [comment]
resolver_file.t has been fixed in latest master branch .https://github.com/alibaba/tengine/pull/1676

And also note that this case will listen on port 53, it should be runned under root permission. ( using `sudo` in github workflow container will make it work
`sudo  prove ...`

**Comment by chobits** [comment]
dynamic_resolve_aaaa.t has been fixed . I rerun job now

**Comment by chobits** [comment]
From ci rerun job, its seems that it dont checkout latest master from alibaba/tengine, it still checkout from ur branch.

HEAD is now at 9f0daa8 Merge cf5bfa01d5f648ed89e0ac0351803a582651a214 into 723f190b8ad322a911ae71d9a1422303eb5d092b


Then you can pull aliabab/tengine to  ur branch firstly, then try `sudo prove` to run test cases in ur ci.yml

**Comment by u5surf** [comment]
@chobits All tengine-tests has passed. Thanks for your cooperation.
Once, I opened this PR from draft. It's pleased for me if you gonna review when you're free.

**Pull request merged**
